package com.geyserextra.paper.pack;

import com.geyserextra.core.api.CustomItemMapping;
import com.geyserextra.core.registry.ItemMappingRegistry;
import com.geyserextra.core.util.JsonUtil;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Collection;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Logger;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

/**
 * Builds a minimal Bedrock resource pack ZIP that maps every detected custom item
 * onto the matching vanilla BE item texture.
 *
 * Why: Geyser's custom item registration assigns each mapping a new BE item ID
 * whose icon is resolved through {@code item_texture.json}. With no resource pack,
 * those IDs render as missing textures. A textureless pack that points every
 * generated icon key at the corresponding vanilla path (e.g. {@code textures/items/diamond_sword})
 * makes the BE client fall back to the bundled vanilla texture, so admins do not
 * need to author a custom pack just to make crafting/recipe-book work.
 *
 * The pack contains only manifest.json, a placeholder icon, and item_texture.json —
 * no PNGs are bundled.
 */
public final class AutoBedrockPackBuilder {

    /**
     * Stable header UUID. Kept constant across regenerations so BE clients
     * recognise re-issued packs as updates rather than entirely new packs.
     */
    private static final String HEADER_UUID = "9d8c1e76-2a3b-4c5d-9e6f-1a2b3c4d5e6f";

    /**
     * Stable resource module UUID, distinct from the header UUID per pack manifest spec.
     */
    private static final String MODULE_UUID = "1f2e3d4c-5b6a-4789-abcd-ef0123456789";

    private static final String PACK_NAME = "GeyserExtra Auto Pack";
    private static final String PACK_DESCRIPTION =
        "Auto-generated by GeyserExtra: maps custom items to vanilla BE textures.";

    private static final String MINECRAFT_NAMESPACE_PREFIX = "minecraft:";
    private static final String VANILLA_TEXTURE_BASE = "textures/items/";

    private AutoBedrockPackBuilder() {}

    /**
     * Builds the pack ZIP at the given output path from the registry contents.
     * Overwrites any existing file. Creates parent directories as needed.
     *
     * <p>Equivalent to {@link #build(ItemMappingRegistry, Path, Path, String, Logger, boolean)}
     * with no Java pack source — every custom item is mapped to its base
     * material's vanilla Bedrock texture.</p>
     *
     * @param registry  source of custom item mappings
     * @param outputZip target ZIP file path (e.g. {@code .../packs/geyserextra_auto.zip})
     * @throws IOException if writing the ZIP fails
     */
    public static void build(ItemMappingRegistry registry, Path outputZip) throws IOException {
        build(registry, outputZip, null, null, null, false);
    }

    /**
     * Builds the pack ZIP, optionally mirroring textures from an operator-provided
     * Java edition resource pack.
     *
     * <p>When {@code javaPackRoot} is non-null and points at an unzipped Java
     * pack directory, the matching {@code (baseItem, custom_model_data)}
     * entries have their PNG textures copied into the BE pack under
     * {@code textures/items/<bedrock_id>.png} and their {@code item_texture.json}
     * entry rewritten to point at that path. Items that have no Java pack
     * counterpart fall back to the vanilla-texture mapping used by
     * {@link #build(ItemMappingRegistry, Path)}.</p>
     *
     * <p>Only 2D textures are copied. 3D model geometry, attachables, and
     * animations are out of scope — operators that need full visual parity
     * should run an external converter (see README).</p>
     *
     * @param registry        source of custom item mappings
     * @param outputZip       target ZIP file path
     * @param javaPackRoot    unzipped Java pack root, or {@code null} to skip Java pack scan
     * @param javaPackFormat  one of {@code AUTO} / {@code LEGACY} / {@code MODERN};
     *                        ignored when {@code javaPackRoot} is null
     * @param logger          plugin logger (may be null when {@code javaPackRoot} is null)
     * @param debug           whether to emit verbose per-file diagnostics
     * @throws IOException if writing the ZIP fails
     */
    public static void build(
        ItemMappingRegistry registry,
        Path outputZip,
        Path javaPackRoot,
        String javaPackFormat,
        Logger logger,
        boolean debug
    ) throws IOException {
        Collection<CustomItemMapping> mappings = registry.getMappings();

        Map<JavaPackReader.CmdKey, JavaPackReader.JavaModelDefinition> javaPackEntries =
            scanJavaPack(javaPackRoot, javaPackFormat, logger, debug);

        Path parent = outputZip.getParent();
        if (parent != null) {
            Files.createDirectories(parent);
        }

        try (ZipOutputStream zos = new ZipOutputStream(Files.newOutputStream(outputZip))) {
            putEntry(zos, "manifest.json",
                buildManifestJson().getBytes(StandardCharsets.UTF_8));
            putEntry(zos, "pack_icon.png", buildPackIconPng());

            // Track which icon keys were satisfied by a Java pack texture so the
            // item_texture.json builder can prefer the copied texture over the
            // vanilla fallback for those entries.
            Map<String, String> customIconToTexturePath = new LinkedHashMap<>();
            int textureCopyCount = 0;
            for (CustomItemMapping mapping : mappings) {
                JavaPackReader.CmdKey key = new JavaPackReader.CmdKey(
                    mapping.baseItem(), mapping.customModelData());
                JavaPackReader.JavaModelDefinition def = javaPackEntries.get(key);
                if (def == null) {
                    continue;
                }
                String bedrockTextureRelative = "textures/items/" + mapping.name();
                String zipEntry = bedrockTextureRelative + ".png";
                try {
                    byte[] pngBytes = Files.readAllBytes(def.textureFile());
                    putEntry(zos, zipEntry, pngBytes);
                    customIconToTexturePath.put(mapping.name(), bedrockTextureRelative);
                    textureCopyCount++;
                    if (debug && logger != null) {
                        logger.fine("[AutoPack] copied " + def.textureFile() + " -> " + zipEntry);
                    }
                } catch (IOException ex) {
                    if (logger != null) {
                        logger.warning("[AutoPack] failed to copy texture for " + key
                            + " from " + def.textureFile() + ": " + ex.getMessage());
                    }
                }
            }

            putEntry(zos, "textures/item_texture.json",
                buildItemTextureJson(mappings, customIconToTexturePath)
                    .getBytes(StandardCharsets.UTF_8));

            if (logger != null && javaPackRoot != null) {
                logger.info("[AutoPack] Java pack texture copy: " + textureCopyCount
                    + " custom textures applied, "
                    + (mappings.size() - textureCopyCount) + " fell back to vanilla");
            }
        }
    }

    /**
     * Runs the Java pack scan with defensive error handling. Returns an empty
     * map on any failure or when the pack root is null.
     */
    private static Map<JavaPackReader.CmdKey, JavaPackReader.JavaModelDefinition> scanJavaPack(
        Path javaPackRoot,
        String javaPackFormat,
        Logger logger,
        boolean debug
    ) {
        if (javaPackRoot == null) {
            return Collections.emptyMap();
        }
        if (logger == null) {
            // No logger means the caller didn't really want a scan.
            return Collections.emptyMap();
        }
        try {
            return new JavaPackReader(javaPackRoot, javaPackFormat, logger, debug).scan();
        } catch (Exception ex) {
            logger.warning("[AutoPack] Java pack scan failed: " + ex.getMessage());
            return Collections.emptyMap();
        }
    }

    private static String buildManifestJson() {
        Map<String, Object> root = new LinkedHashMap<>();
        root.put("format_version", 2);

        Map<String, Object> header = new LinkedHashMap<>();
        header.put("name", PACK_NAME);
        header.put("description", PACK_DESCRIPTION);
        header.put("uuid", HEADER_UUID);
        header.put("version", List.of(1, 0, 0));
        header.put("min_engine_version", List.of(1, 16, 100));
        root.put("header", header);

        Map<String, Object> module = new LinkedHashMap<>();
        module.put("type", "resources");
        module.put("uuid", MODULE_UUID);
        module.put("version", List.of(1, 0, 0));
        root.put("modules", List.of(module));

        return JsonUtil.toPrettyJson(root);
    }

    private static String buildItemTextureJson(Collection<CustomItemMapping> mappings) {
        return buildItemTextureJson(mappings, Collections.emptyMap());
    }

    /**
     * @param customIconToTexturePath icon-key -> custom texture path (without
     *        the trailing {@code .png}) for items whose textures were copied
     *        from the Java pack. Missing entries fall back to the vanilla
     *        Bedrock texture for the base item.
     */
    private static String buildItemTextureJson(
        Collection<CustomItemMapping> mappings,
        Map<String, String> customIconToTexturePath
    ) {
        Map<String, Object> root = new LinkedHashMap<>();
        root.put("resource_pack_name", "geyserextra_auto");
        root.put("texture_name", "atlas.items");

        Map<String, Map<String, String>> textureData = new LinkedHashMap<>();
        for (CustomItemMapping mapping : mappings) {
            // The mapping name is what CustomItemsHandler sends to Geyser as `name`.
            // Geyser uses that name as the icon key when no explicit icon is set,
            // so this entry must match it exactly.
            String iconKey = mapping.name();
            String texturePath = customIconToTexturePath.getOrDefault(
                iconKey,
                vanillaTexturePathFor(mapping.baseItem())
            );
            Map<String, String> entry = new LinkedHashMap<>();
            entry.put("textures", texturePath);
            textureData.put(iconKey, entry);
        }
        root.put("texture_data", textureData);

        return JsonUtil.toPrettyJson(root);
    }

    /**
     * Maps a Java-side base item identifier to the BE vanilla texture path.
     *
     * Most JE/BE item names align (diamond_sword, copper_sword, arrow, snowball...).
     * BE clients resolve {@code textures/items/<name>} against the bundled vanilla
     * resource pack when no override exists in our pack, which is the desired fallback.
     */
    private static String vanillaTexturePathFor(String baseItem) {
        String name = baseItem.startsWith(MINECRAFT_NAMESPACE_PREFIX)
            ? baseItem.substring(MINECRAFT_NAMESPACE_PREFIX.length())
            : baseItem;
        return VANILLA_TEXTURE_BASE + name;
    }

    /**
     * Builds a 64x64 single-colour PNG used as the pack icon. BE rejects packs
     * without a {@code pack_icon.png}; the actual contents are unimportant.
     */
    private static byte[] buildPackIconPng() throws IOException {
        BufferedImage img = new BufferedImage(64, 64, BufferedImage.TYPE_INT_ARGB);
        int color = 0xFF60A0F0;
        for (int y = 0; y < 64; y++) {
            for (int x = 0; x < 64; x++) {
                img.setRGB(x, y, color);
            }
        }
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        ImageIO.write(img, "png", bos);
        return bos.toByteArray();
    }

    private static void putEntry(ZipOutputStream zos, String entryName, byte[] data) throws IOException {
        ZipEntry entry = new ZipEntry(entryName);
        zos.putNextEntry(entry);
        zos.write(data);
        zos.closeEntry();
    }
}
