package com.geyserextra.paper.pack;

import com.geyserextra.core.api.CustomItemMapping;
import com.geyserextra.core.registry.ItemMappingRegistry;
import com.geyserextra.core.util.JsonUtil;

import org.bukkit.Material;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

/**
 * Builds a Bedrock resource pack ZIP that mirrors the operator-supplied Java
 * pack's custom textures onto Geyser-registered custom items, with a vanilla
 * texture fallback for everything else.
 *
 * <p>Why: Geyser's custom item registration assigns each mapping a new BE item
 * ID whose icon is resolved through {@code item_texture.json}. Without a
 * companion BE pack — or with an entry-less one — those IDs render as missing
 * (transparent) textures on Bedrock clients.</p>
 *
 * <p><b>Texture resolution per mapping:</b>
 * <ul>
 *   <li>Java pack supplies a custom PNG → copy it under
 *       {@code textures/items/&lt;iconKey&gt;.png} and point the
 *       {@code item_texture.json} entry at that path. Bedrock sees the
 *       same artwork a Java player does.</li>
 *   <li>Java pack supplies no PNG for this mapping (or no Java pack at all)
 *       → write a vanilla fallback entry pointing at the base material's
 *       built-in Bedrock texture path ({@code textures/items/&lt;baseName&gt;}).
 *       Bedrock falls back to its bundled vanilla artwork rather than
 *       rendering a transparent slot, matching what a Java player without
 *       the pack would see.</li>
 * </ul>
 * </p>
 *
 * <p>The pack contains {@code manifest.json}, a placeholder
 * {@code pack_icon.png}, any copied PNG textures, and the
 * {@code item_texture.json}.</p>
 */
public final class AutoBedrockPackBuilder {

    /**
     * Stable header UUID. Kept constant across regenerations so BE clients
     * recognise re-issued packs as updates rather than entirely new packs.
     */
    private static final String HEADER_UUID = "9d8c1e76-2a3b-4c5d-9e6f-1a2b3c4d5e6f";

    /**
     * Stable resource module UUID, distinct from the header UUID per pack manifest spec.
     */
    private static final String MODULE_UUID = "1f2e3d4c-5b6a-4789-abcd-ef0123456789";

    private static final String PACK_NAME = "GeyserExtra Auto Pack";
    private static final String PACK_DESCRIPTION =
        "Auto-generated by GeyserExtra: maps custom items to vanilla BE textures.";

    private static final String MINECRAFT_NAMESPACE_PREFIX = "minecraft:";
    private static final String VANILLA_TEXTURE_BASE = "textures/items/";

    /**
     * Same regex Extension's {@code CustomItemsHandler.sanitizeIdentifierValue}
     * applies to {@code mapping.name()} before it becomes the Geyser icon key.
     * The auto-pack must mirror that transform on the Paper side so the BE
     * {@code item_texture.json} key and the ZIP texture path agree with what
     * Extension registers as the item's icon. Without this, mapping names
     * containing characters Extension rewrites (notably {@code ':'} from
     * PDC-derived names) cause a lookup mismatch and the texture is never
     * applied on Bedrock even though it exists on disk.
     */
    private static final Pattern BEDROCK_ICON_KEY_INVALID = Pattern.compile("[^a-z0-9_\\-./]");

    private AutoBedrockPackBuilder() {}

    /**
     * Sanitizes a registry mapping name into the icon-key form Geyser's
     * extension side ultimately registers. Lower-cases the input and replaces
     * any character outside {@code [a-z0-9_./-]} with {@code '_'}.
     */
    private static String toBedrockIconKey(String mappingName) {
        if (mappingName == null || mappingName.isEmpty()) {
            return "";
        }
        return BEDROCK_ICON_KEY_INVALID.matcher(mappingName.toLowerCase()).replaceAll("_");
    }

    /**
     * Builds the pack ZIP at the given output path from the registry contents.
     * Overwrites any existing file. Creates parent directories as needed.
     *
     * <p>Equivalent to {@link #build(ItemMappingRegistry, Path, Path, String, Logger, boolean)}
     * with no Java pack source — every custom item is mapped to its base
     * material's vanilla Bedrock texture.</p>
     *
     * @param registry  source of custom item mappings
     * @param outputZip target ZIP file path (e.g. {@code .../packs/geyserextra_auto.zip})
     * @throws IOException if writing the ZIP fails
     */
    public static void build(ItemMappingRegistry registry, Path outputZip) throws IOException {
        build(registry, outputZip, null, null, null, false);
    }

    /**
     * Builds the pack ZIP, optionally mirroring textures from an operator-provided
     * Java edition resource pack.
     *
     * <p>When {@code javaPackRoot} is non-null and points at an unzipped Java
     * pack directory, the matching {@code (baseItem, custom_model_data)}
     * entries have their PNG textures copied into the BE pack under
     * {@code textures/items/<bedrock_id>.png} and their {@code item_texture.json}
     * entry rewritten to point at that path. Items that have no Java pack
     * counterpart fall back to the vanilla-texture mapping used by
     * {@link #build(ItemMappingRegistry, Path)}.</p>
     *
     * <p>Only 2D textures are copied. 3D model geometry, attachables, and
     * animations are out of scope — operators that need full visual parity
     * should run an external converter (see README).</p>
     *
     * @param registry        source of custom item mappings
     * @param outputZip       target ZIP file path
     * @param javaPackRoot    unzipped Java pack root, or {@code null} to skip Java pack scan
     * @param javaPackFormat  one of {@code AUTO} / {@code LEGACY} / {@code MODERN};
     *                        ignored when {@code javaPackRoot} is null
     * @param logger          plugin logger (may be null when {@code javaPackRoot} is null)
     * @param debug           whether to emit verbose per-file diagnostics
     * @throws IOException if writing the ZIP fails
     */
    public static void build(
        ItemMappingRegistry registry,
        Path outputZip,
        Path javaPackRoot,
        String javaPackFormat,
        Logger logger,
        boolean debug
    ) throws IOException {
        Map<JavaPackReader.CmdKey, JavaPackReader.JavaModelDefinition> javaPackEntries =
            scanJavaPack(javaPackRoot, javaPackFormat, logger, debug);
        build(registry, outputZip, javaPackEntries, logger, debug);
    }

    /**
     * Builds the pack ZIP using already-scanned Java pack entries.
     *
     * <p>Use this overload when the caller has already invoked
     * {@link JavaPackReader#scan()} once for an earlier step (such as
     * pre-populating the registry) and wants to avoid re-reading every
     * model JSON a second time.</p>
     *
     * @param registry          source of custom item mappings
     * @param outputZip         target ZIP file path
     * @param javaPackEntries   pre-scanned Java pack overrides; pass
     *                          {@link Collections#emptyMap()} to skip the
     *                          texture-copy step entirely
     * @param logger            plugin logger (must not be null when pack
     *                          entries are present)
     * @param debug             whether to emit verbose per-file diagnostics
     * @throws IOException if writing the ZIP fails
     */
    public static void build(
        ItemMappingRegistry registry,
        Path outputZip,
        Map<JavaPackReader.CmdKey, JavaPackReader.JavaModelDefinition> javaPackEntries,
        Logger logger,
        boolean debug
    ) throws IOException {
        Collection<CustomItemMapping> mappings = registry.getMappings();
        if (javaPackEntries == null) {
            javaPackEntries = Collections.emptyMap();
        }

        Path parent = outputZip.getParent();
        if (parent != null) {
            Files.createDirectories(parent);
        }

        // Phase 1 — plan the PNG copies (without writing yet) so we know the
        // final customIconToTexturePath before we serialize the manifest.
        // Writing PNGs to disk only happens inside phase 3 below, against the
        // tmp file. This separation also lets phase 2 hash the rendered
        // item_texture.json without re-serializing on the hot write path.
        Map<String, String> customIconToTexturePath = new LinkedHashMap<>();
        List<TextureCopyTask> pngTasks = new ArrayList<>();
        Set<String> plannedZipEntries = new HashSet<>();
        int duplicateSkipCount = 0;
        for (CustomItemMapping mapping : mappings) {
            JavaPackReader.CmdKey key = new JavaPackReader.CmdKey(
                mapping.baseItem(), mapping.customModelData());
            JavaPackReader.JavaModelDefinition def = javaPackEntries.get(key);
            if (def == null) {
                continue;
            }
            String iconKey = toBedrockIconKey(mapping.name());
            String bedrockTextureRelative = "textures/items/" + iconKey;
            String zipEntry = bedrockTextureRelative + ".png";
            if (!plannedZipEntries.add(zipEntry)) {
                duplicateSkipCount++;
                if (logger != null) {
                    logger.warning("[AutoPack] duplicate ZIP entry skipped (mapping name "
                        + "collides with already-written entry): " + zipEntry
                        + " (mapping=" + mapping.name() + ", key=" + key + ")");
                }
                continue;
            }
            pngTasks.add(new TextureCopyTask(def.textureFile(), zipEntry, key.toString()));
            customIconToTexturePath.put(iconKey, bedrockTextureRelative);
        }

        // Phase 2 — render item_texture.json from the finalised iconKey map
        // and derive a content-addressed patch version. The patch version
        // changes whenever item_texture.json changes, which is what tells
        // Bedrock clients "this is a new pack, drop your cached copy". Without
        // this the manifest UUID + version pair stays constant across pack
        // regenerations and the client silently keeps using stale textures.
        String itemTextureJson = buildItemTextureJson(mappings, customIconToTexturePath, logger, debug);
        int patchVersion = patchVersionFromContent(itemTextureJson);
        String manifestJson = buildManifestJson(patchVersion);

        // Phase 3 — write everything to a sibling .tmp file, then atomic-move
        // into place. Without the tmp + atomic move, a Bedrock client
        // streaming the previous pack mid-regeneration would read a corrupt
        // (truncated) ZIP because Files.newOutputStream defaults to
        // CREATE + TRUNCATE_EXISTING. The atomic move guarantees the visible
        // file flips from one valid ZIP to the next in a single filesystem
        // operation; readers only ever see complete packs.
        Path tmpZip = outputZip.resolveSibling(outputZip.getFileName() + ".tmp");
        Set<String> writtenEntries = new HashSet<>();
        int textureCopyCount = 0;
        try (ZipOutputStream zos = new ZipOutputStream(Files.newOutputStream(tmpZip))) {
            putEntryUnique(zos, "manifest.json",
                manifestJson.getBytes(StandardCharsets.UTF_8), writtenEntries, logger);
            putEntryUnique(zos, "pack_icon.png", buildPackIconPng(), writtenEntries, logger);

            for (TextureCopyTask task : pngTasks) {
                try {
                    byte[] pngBytes = Files.readAllBytes(task.source());
                    putEntryUnique(zos, task.zipEntry(), pngBytes, writtenEntries, logger);
                    textureCopyCount++;
                    if (debug && logger != null) {
                        logger.fine("[AutoPack] copied " + task.source() + " -> " + task.zipEntry());
                    }
                } catch (IOException ex) {
                    if (logger != null) {
                        logger.warning("[AutoPack] failed to copy texture for " + task.keyLabel()
                            + " from " + task.source() + ": " + ex.getMessage());
                    }
                }
            }

            putEntryUnique(zos, "textures/item_texture.json",
                itemTextureJson.getBytes(StandardCharsets.UTF_8), writtenEntries, logger);
        } catch (IOException ioEx) {
            // Failed to fully write the tmp file — make sure it doesn't
            // accumulate on disk before propagating the error.
            try {
                Files.deleteIfExists(tmpZip);
            } catch (IOException cleanupEx) {
                if (logger != null) {
                    logger.log(Level.WARNING,
                        "[AutoPack] failed to clean up tmp file after write error", cleanupEx);
                }
            }
            throw ioEx;
        }

        try {
            Files.move(tmpZip, outputZip,
                StandardCopyOption.REPLACE_EXISTING,
                StandardCopyOption.ATOMIC_MOVE);
        } catch (IOException atomicEx) {
            // Some filesystems (e.g. cross-mount, certain Windows network
            // shares) don't support ATOMIC_MOVE. Fall back to REPLACE_EXISTING
            // alone — the worst case is a brief window where a concurrent
            // reader sees the new file in a partially-readable state, which
            // is still strictly better than the previous "truncate then
            // append" path.
            if (logger != null) {
                logger.warning("[AutoPack] atomic move not supported on this filesystem ("
                    + atomicEx.getMessage() + "); falling back to non-atomic replace");
            }
            Files.move(tmpZip, outputZip, StandardCopyOption.REPLACE_EXISTING);
        }

        if (logger != null && !javaPackEntries.isEmpty()) {
            logger.info("[AutoPack] Java pack texture copy: " + textureCopyCount
                + " custom textures applied, "
                + (mappings.size() - textureCopyCount - duplicateSkipCount)
                + " fell back to vanilla, "
                + duplicateSkipCount + " skipped due to duplicate ZIP entry name");
        }
    }

    /**
     * Hashes {@code itemTextureJson} into a 0..32767 integer suitable for use
     * as the patch component of the pack's semantic version. Bedrock treats
     * a (UUID, version) pair as the cache key for resource packs — keeping
     * version[2] tied to content means clients automatically download a
     * fresh copy whenever the registry changes, instead of silently re-using
     * a stale cached pack that no longer matches the live mappings.
     *
     * <p>Range is clamped to 0..32767 because some Bedrock manifest parsers
     * treat each version component as a signed short. SHA-256 is overkill
     * for the collision space we need but is the only reliably-available
     * algorithm in the JDK platform, and the cost is negligible at the
     * mappings.size() scale we handle.</p>
     */
    private static int patchVersionFromContent(String itemTextureJson) {
        if (itemTextureJson == null || itemTextureJson.isEmpty()) {
            return 0;
        }
        try {
            byte[] digest = MessageDigest.getInstance("SHA-256")
                .digest(itemTextureJson.getBytes(StandardCharsets.UTF_8));
            int value = 0;
            for (int i = 0; i < 4 && i < digest.length; i++) {
                value = (value << 8) | (digest[i] & 0xFF);
            }
            return Math.abs(value) % 32768;
        } catch (NoSuchAlgorithmException ex) {
            // SHA-256 is required by every JDK platform per JEP 414 / spec;
            // this branch should be unreachable. Return 0 as a deterministic
            // fallback rather than throwing — the pack still works without
            // cache busting, just less efficiently.
            return 0;
        }
    }

    /**
     * Planning record for a single Java-pack PNG that will be copied into the
     * generated ZIP. Held in a list so phase 1 (planning) can complete
     * before phase 3 (writing) begins, which is what lets us hash the final
     * item_texture.json into the manifest version without re-walking the
     * mapping set twice.
     */
    private record TextureCopyTask(Path source, String zipEntry, String keyLabel) {}

    /**
     * Writes a ZIP entry only if its name hasn't been used yet. Records the
     * name in {@code writtenEntries}; on duplicate, logs and skips.
     */
    private static void putEntryUnique(
        ZipOutputStream zos,
        String entryName,
        byte[] data,
        Set<String> writtenEntries,
        Logger logger
    ) throws IOException {
        if (!writtenEntries.add(entryName)) {
            if (logger != null) {
                logger.warning("[AutoPack] duplicate ZIP entry skipped: " + entryName);
            }
            return;
        }
        putEntry(zos, entryName, data);
    }

    /**
     * Runs the Java pack scan with defensive error handling. Returns an empty
     * map on any failure or when the pack root is null.
     */
    private static Map<JavaPackReader.CmdKey, JavaPackReader.JavaModelDefinition> scanJavaPack(
        Path javaPackRoot,
        String javaPackFormat,
        Logger logger,
        boolean debug
    ) {
        if (javaPackRoot == null) {
            return Collections.emptyMap();
        }
        if (logger == null) {
            // No logger means the caller didn't really want a scan.
            return Collections.emptyMap();
        }
        try {
            return new JavaPackReader(javaPackRoot, javaPackFormat, logger, debug).scan();
        } catch (Exception ex) {
            logger.warning("[AutoPack] Java pack scan failed: " + ex.getMessage());
            return Collections.emptyMap();
        }
    }

    /**
     * Renders the pack manifest with the given {@code patchVersion} embedded
     * as the third component of both the header and module {@code version}
     * tuples. The header and module versions move in lockstep because
     * Bedrock clients accept (but warn about) a mismatch; keeping them
     * aligned avoids the warning entirely.
     */
    private static String buildManifestJson(int patchVersion) {
        Map<String, Object> root = new LinkedHashMap<>();
        root.put("format_version", 2);

        List<Integer> version = List.of(1, 0, patchVersion);

        Map<String, Object> header = new LinkedHashMap<>();
        header.put("name", PACK_NAME);
        header.put("description", PACK_DESCRIPTION);
        header.put("uuid", HEADER_UUID);
        header.put("version", version);
        header.put("min_engine_version", List.of(1, 16, 100));
        root.put("header", header);

        Map<String, Object> module = new LinkedHashMap<>();
        module.put("type", "resources");
        module.put("uuid", MODULE_UUID);
        module.put("version", version);
        root.put("modules", List.of(module));

        return JsonUtil.toPrettyJson(root);
    }

    private static String buildItemTextureJson(Collection<CustomItemMapping> mappings) {
        return buildItemTextureJson(mappings, Collections.emptyMap(), null, false);
    }

    /**
     * Builds the {@code item_texture.json}: every registered mapping gets an
     * entry, pointed at either the operator-supplied Java pack PNG (when
     * present in {@code customIconToTexturePath}) or the base material's
     * built-in Bedrock texture path as a vanilla fallback.
     *
     * <p>Why the vanilla fallback rather than a strict opt-out: skipping
     * mappings without a custom PNG would leave the matching Bedrock item ID
     * texture-less, and the Bedrock client renders that as a transparent
     * slot. Falling back to the base material's texture keeps the item
     * visible — exactly what a Java player without the resource pack would
     * see — while still letting the Java pack override individual items.</p>
     *
     * @param customIconToTexturePath icon-key -> custom texture path (without
     *        the trailing {@code .png}) for items whose textures were copied
     *        from the Java pack. Missing entries fall back to the vanilla
     *        Bedrock texture for the base item.
     * @param logger optional logger; when non-null, warns once per icon-key
     *        collision so an operator can see when two distinct mappings
     *        collapse to the same Bedrock identity (one will lose its
     *        texture).
     */
    private static String buildItemTextureJson(
        Collection<CustomItemMapping> mappings,
        Map<String, String> customIconToTexturePath,
        Logger logger,
        boolean debug
    ) {
        Map<String, Object> root = new LinkedHashMap<>();
        root.put("resource_pack_name", "geyserextra_auto");
        root.put("texture_name", "atlas.items");

        Map<String, Map<String, String>> textureData = new LinkedHashMap<>();
        Map<String, String> seenIconKeys = new LinkedHashMap<>();  // iconKey -> first mapping name that claimed it
        int customCount = 0;
        int vanillaFallbackCount = 0;
        int skippedCollision = 0;
        int skippedNoVanilla = 0;
        for (CustomItemMapping mapping : mappings) {
            // Sanitize to the same form Extension's CustomItemsHandler uses when
            // registering the icon key. Without this transform, mapping names
            // containing characters Extension rewrites (notably ':') would
            // produce a key here that does not match the registered icon, and
            // Bedrock would silently fail to find the texture.
            String iconKey = toBedrockIconKey(mapping.name());
            // Dedup: if multiple registry entries collapse to the same sanitized
            // key, only the first wins. Surface this loudly so an operator can
            // rename the offender; with a silent skip the texture-not-applied
            // result would be invisible to diagnostics.
            String previous = seenIconKeys.putIfAbsent(iconKey, mapping.name());
            if (previous != null) {
                if (logger != null) {
                    logger.warning("[AutoPack] icon-key collision: '" + iconKey
                        + "' claimed by '" + previous + "', dropping later mapping '"
                        + mapping.name() + "' (texture will not be applied for the duplicate)");
                }
                skippedCollision++;
                continue;
            }
            String customPath = customIconToTexturePath.get(iconKey);
            String texturePath;
            if (customPath != null) {
                texturePath = customPath;
                customCount++;
            } else {
                texturePath = vanillaTexturePathFor(mapping.baseItem());
                if (texturePath == null) {
                    // Modded namespace / unresolvable base item — no Bedrock
                    // vanilla counterpart exists. Writing an entry here with
                    // a synthesised "textures/items/mymod:sword"-style path
                    // would surface as a missing-texture purple/black checker
                    // on every Bedrock client. Drop the entry and warn so
                    // the operator can supply a manual Bedrock texture if
                    // they want a visual for this item.
                    if (logger != null) {
                        logger.warning("[AutoPack] no Bedrock vanilla fallback for "
                            + mapping.baseItem() + " (iconKey=" + iconKey
                            + "); skipping item_texture entry — operator must "
                            + "ship a custom Bedrock pack texture or rely on "
                            + "Geyser's default rendering for this item");
                    }
                    skippedNoVanilla++;
                    continue;
                }
                vanillaFallbackCount++;
                // Per-entry log at debug=true so an operator who reports
                // "this Bedrock item shows a missing/wrong texture" can
                // cross-reference the iconKey to find which base material
                // path was assumed and verify the BE vanilla texture
                // actually exists under that path on Bedrock 1.21+.
                if (logger != null && debug) {
                    logger.info("[AutoPack] vanilla-fallback: " + mapping.baseItem()
                        + "#" + mapping.customModelData()
                        + " (iconKey=" + iconKey + ") -> " + texturePath);
                }
            }
            Map<String, String> entry = new LinkedHashMap<>();
            entry.put("textures", texturePath);
            textureData.put(iconKey, entry);
        }
        root.put("texture_data", textureData);

        if (logger != null && textureData.size() > 0) {
            logger.info("[AutoPack] item_texture.json: wrote " + textureData.size()
                + " entries (" + customCount + " custom, "
                + vanillaFallbackCount + " vanilla fallback, "
                + skippedCollision + " skipped due to icon-key collision, "
                + skippedNoVanilla + " skipped for missing vanilla fallback)");
        }

        return JsonUtil.toPrettyJson(root);
    }

    /** Bedrock vanilla texture root for block-base items ({@code stone}, {@code oak_log}, …). */
    private static final String VANILLA_BLOCK_TEXTURE_BASE = "textures/blocks/";

    /**
     * Maps a Java-side base item identifier to the BE vanilla texture path,
     * or {@code null} when no Bedrock vanilla texture exists for the
     * identifier (e.g. a modded namespace).
     *
     * <p>Bedrock's vanilla resource pack splits textures by type:
     * <ul>
     *   <li>Plain items (sword, paper, arrow, food, …) live under
     *       {@code textures/items/}.</li>
     *   <li>Block-as-item textures (stone, oak_log, dirt, …) live under
     *       {@code textures/blocks/}.</li>
     * </ul>
     * Hard-coding {@code textures/items/<name>} unconditionally — the
     * earlier behaviour — pointed every block-base CMD entry at a path
     * that doesn't exist in Bedrock vanilla and surfaced as a missing-
     * texture purple/black checker on the client. We now consult
     * {@link Material#isBlock()} when the identifier resolves to a known
     * Material and prefix the correct directory.</p>
     *
     * <p><b>Modded namespaces</b>: a base identifier like {@code mymod:sword}
     * has no Bedrock vanilla counterpart, and writing it into a path would
     * produce {@code textures/items/mymod:sword} which Bedrock treats as
     * invalid (the {@code ':'} is illegal in resource paths). For these
     * the method returns {@code null}; the caller must drop the
     * {@code item_texture.json} entry entirely. Operators who want a
     * Bedrock-side visual for a modded base item must supply a custom
     * texture via the Java pack mirror or a hand-authored Bedrock pack.</p>
     */
    private static String vanillaTexturePathFor(String baseItem) {
        if (baseItem == null || baseItem.isBlank()) {
            return null;
        }
        String name;
        if (baseItem.startsWith(MINECRAFT_NAMESPACE_PREFIX)) {
            name = baseItem.substring(MINECRAFT_NAMESPACE_PREFIX.length());
        } else if (baseItem.indexOf(':') < 0) {
            // No namespace — treat as vanilla (Bukkit's matchMaterial defaults
            // to minecraft: when fed an unqualified name).
            name = baseItem;
        } else {
            // Modded namespace (mymod:sword, etc.). Bedrock has no
            // counterpart, so signal "no fallback" rather than synthesising
            // an invalid path.
            return null;
        }
        if (isBlockBaseItem(baseItem)) {
            return VANILLA_BLOCK_TEXTURE_BASE + name;
        }
        return VANILLA_TEXTURE_BASE + name;
    }

    /**
     * Whether the supplied {@code namespace:name} identifier resolves to a
     * Bukkit {@link Material} that lives in the block category. Wrapped in
     * a try/catch so a modded namespace ({@code mymod:something}) — which
     * {@link Material#matchMaterial} cannot resolve — degrades to
     * {@code false} (item fallback) rather than throwing.
     */
    private static boolean isBlockBaseItem(String baseItem) {
        try {
            Material material = Material.matchMaterial(baseItem);
            return material != null && material.isBlock();
        } catch (Throwable t) {
            return false;
        }
    }

    /**
     * Builds a 64x64 single-colour PNG used as the pack icon. BE rejects packs
     * without a {@code pack_icon.png}; the actual contents are unimportant.
     */
    private static byte[] buildPackIconPng() throws IOException {
        BufferedImage img = new BufferedImage(64, 64, BufferedImage.TYPE_INT_ARGB);
        int color = 0xFF60A0F0;
        for (int y = 0; y < 64; y++) {
            for (int x = 0; x < 64; x++) {
                img.setRGB(x, y, color);
            }
        }
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        ImageIO.write(img, "png", bos);
        return bos.toByteArray();
    }

    private static void putEntry(ZipOutputStream zos, String entryName, byte[] data) throws IOException {
        ZipEntry entry = new ZipEntry(entryName);
        zos.putNextEntry(entry);
        zos.write(data);
        zos.closeEntry();
    }
}
