package com.geyserextra.paper.pack;

import com.geyserextra.core.api.CustomItemMapping;
import com.geyserextra.core.registry.ItemMappingRegistry;
import com.geyserextra.core.util.JsonUtil;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Collection;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

/**
 * Builds a minimal Bedrock resource pack ZIP that maps every detected custom item
 * onto the matching vanilla BE item texture.
 *
 * Why: Geyser's custom item registration assigns each mapping a new BE item ID
 * whose icon is resolved through {@code item_texture.json}. With no resource pack,
 * those IDs render as missing textures. A textureless pack that points every
 * generated icon key at the corresponding vanilla path (e.g. {@code textures/items/diamond_sword})
 * makes the BE client fall back to the bundled vanilla texture, so admins do not
 * need to author a custom pack just to make crafting/recipe-book work.
 *
 * The pack contains only manifest.json, a placeholder icon, and item_texture.json —
 * no PNGs are bundled.
 */
public final class AutoBedrockPackBuilder {

    /**
     * Stable header UUID. Kept constant across regenerations so BE clients
     * recognise re-issued packs as updates rather than entirely new packs.
     */
    private static final String HEADER_UUID = "9d8c1e76-2a3b-4c5d-9e6f-1a2b3c4d5e6f";

    /**
     * Stable resource module UUID, distinct from the header UUID per pack manifest spec.
     */
    private static final String MODULE_UUID = "1f2e3d4c-5b6a-4789-abcd-ef0123456789";

    private static final String PACK_NAME = "GeyserExtra Auto Pack";
    private static final String PACK_DESCRIPTION =
        "Auto-generated by GeyserExtra: maps custom items to vanilla BE textures.";

    private static final String MINECRAFT_NAMESPACE_PREFIX = "minecraft:";
    private static final String VANILLA_TEXTURE_BASE = "textures/items/";

    private AutoBedrockPackBuilder() {}

    /**
     * Builds the pack ZIP at the given output path from the registry contents.
     * Overwrites any existing file. Creates parent directories as needed.
     *
     * @param registry  source of custom item mappings
     * @param outputZip target ZIP file path (e.g. {@code .../packs/geyserextra_auto.zip})
     * @throws IOException if writing the ZIP fails
     */
    public static void build(ItemMappingRegistry registry, Path outputZip) throws IOException {
        Collection<CustomItemMapping> mappings = registry.getMappings();

        Path parent = outputZip.getParent();
        if (parent != null) {
            Files.createDirectories(parent);
        }

        try (ZipOutputStream zos = new ZipOutputStream(Files.newOutputStream(outputZip))) {
            putEntry(zos, "manifest.json",
                buildManifestJson().getBytes(StandardCharsets.UTF_8));
            putEntry(zos, "pack_icon.png", buildPackIconPng());
            putEntry(zos, "textures/item_texture.json",
                buildItemTextureJson(mappings).getBytes(StandardCharsets.UTF_8));
        }
    }

    private static String buildManifestJson() {
        Map<String, Object> root = new LinkedHashMap<>();
        root.put("format_version", 2);

        Map<String, Object> header = new LinkedHashMap<>();
        header.put("name", PACK_NAME);
        header.put("description", PACK_DESCRIPTION);
        header.put("uuid", HEADER_UUID);
        header.put("version", List.of(1, 0, 0));
        header.put("min_engine_version", List.of(1, 16, 100));
        root.put("header", header);

        Map<String, Object> module = new LinkedHashMap<>();
        module.put("type", "resources");
        module.put("uuid", MODULE_UUID);
        module.put("version", List.of(1, 0, 0));
        root.put("modules", List.of(module));

        return JsonUtil.toPrettyJson(root);
    }

    private static String buildItemTextureJson(Collection<CustomItemMapping> mappings) {
        Map<String, Object> root = new LinkedHashMap<>();
        root.put("resource_pack_name", "geyserextra_auto");
        root.put("texture_name", "atlas.items");

        Map<String, Map<String, String>> textureData = new LinkedHashMap<>();
        for (CustomItemMapping mapping : mappings) {
            // The mapping name is what CustomItemsHandler sends to Geyser as `name`.
            // Geyser uses that name as the icon key when no explicit icon is set,
            // so this entry must match it exactly.
            String iconKey = mapping.name();
            String texturePath = vanillaTexturePathFor(mapping.baseItem());
            Map<String, String> entry = new LinkedHashMap<>();
            entry.put("textures", texturePath);
            textureData.put(iconKey, entry);
        }
        root.put("texture_data", textureData);

        return JsonUtil.toPrettyJson(root);
    }

    /**
     * Maps a Java-side base item identifier to the BE vanilla texture path.
     *
     * Most JE/BE item names align (diamond_sword, copper_sword, arrow, snowball...).
     * BE clients resolve {@code textures/items/<name>} against the bundled vanilla
     * resource pack when no override exists in our pack, which is the desired fallback.
     */
    private static String vanillaTexturePathFor(String baseItem) {
        String name = baseItem.startsWith(MINECRAFT_NAMESPACE_PREFIX)
            ? baseItem.substring(MINECRAFT_NAMESPACE_PREFIX.length())
            : baseItem;
        return VANILLA_TEXTURE_BASE + name;
    }

    /**
     * Builds a 64x64 single-colour PNG used as the pack icon. BE rejects packs
     * without a {@code pack_icon.png}; the actual contents are unimportant.
     */
    private static byte[] buildPackIconPng() throws IOException {
        BufferedImage img = new BufferedImage(64, 64, BufferedImage.TYPE_INT_ARGB);
        int color = 0xFF60A0F0;
        for (int y = 0; y < 64; y++) {
            for (int x = 0; x < 64; x++) {
                img.setRGB(x, y, color);
            }
        }
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        ImageIO.write(img, "png", bos);
        return bos.toByteArray();
    }

    private static void putEntry(ZipOutputStream zos, String entryName, byte[] data) throws IOException {
        ZipEntry entry = new ZipEntry(entryName);
        zos.putNextEntry(entry);
        zos.write(data);
        zos.closeEntry();
    }
}
