package com.geyserextra.core.util;

import java.util.Locale;

/**
 * Generates Bedrock cooldown categories that are unique per custom mapping.
 *
 * <p>The category is shared by the Paper-side cooldown bridge and the Geyser
 * custom-item definition. Keeping it in core prevents the two modules from
 * silently drifting back to base-material categories.</p>
 */
public final class CustomItemCooldownGroups {

    public static final String NAMESPACE = "geyserextra";
    private static final String PREFIX = NAMESPACE + ":";

    private CustomItemCooldownGroups() {}

    /**
     * Returns a deterministic namespaced cooldown group for a mapping name.
     *
     * @param mappingName custom mapping identifier
     * @return {@code geyserextra:<sanitized-name>}, or {@code null} when blank
     */
    public static String forMapping(String mappingName) {
        if (mappingName == null || mappingName.isBlank()) {
            return null;
        }
        String normalized = mappingName.trim().toLowerCase(Locale.ROOT)
            .replaceAll("[^a-z0-9._/-]+", "_")
            .replaceAll("^_+|_+$", "");
        return normalized.isEmpty() ? null : PREFIX + normalized;
    }

    /**
     * Whether a cooldown group was generated by GeyserExtra.
     */
    public static boolean isSynthetic(String group) {
        return group != null && group.startsWith(PREFIX);
    }
}
